@extends('layouts.app')

@section('content')
<div class="d-flex justify-content-between align-items-center mb-3">
    <h2 class="mb-0">Receipt Details</h2>
    <div class="d-flex gap-2">
        <a href="{{ route('receipts.view', $receipt) }}" class="btn btn-primary" target="_blank">View / Print</a>
        <a href="{{ route('receipts.download', $receipt) }}" class="btn btn-outline-primary">Download PDF</a>
        <a href="{{ route('receipts.index') }}" class="btn btn-outline-secondary">Back</a>
    </div>
</div>

<div class="card shadow-sm border-0">
    <div class="card-body">
        <div class="row g-3">
            <div class="col-md-4">
                <div class="text-muted small">Receipt Number</div>
                <div class="fw-semibold">{{ $receipt->receipt_number }}</div>
            </div>
            <div class="col-md-4">
                <div class="text-muted small">Member</div>
                <div class="fw-semibold">{{ $receipt->member->full_name ?? 'General Income' }}</div>
            </div>
            <div class="col-md-4">
                <div class="text-muted small">Amount</div>
                <div class="fw-semibold">GHS {{ number_format($receipt->amount, 2) }}</div>
            </div>
            <div class="col-md-4">
                <div class="text-muted small">Payment Type</div>
                <div class="fw-semibold">{{ $paymentLabel }}</div>
            </div>
            <div class="col-md-4">
                <div class="text-muted small">Generated By</div>
                <div class="fw-semibold">{{ $receipt->generatedBy->name ?? '-' }}</div>
            </div>
            <div class="col-md-4">
                <div class="text-muted small">Generated At</div>
                <div class="fw-semibold">{{ $receipt->created_at->format('Y-m-d H:i') }}</div>
            </div>
        </div>
    </div>
</div>
@endsection
